#!/bin/bash
# vim: filetype=sh
# Source global definitions
if [[ -f "${HOME}/.all_bashrc" ]]; then
    source "${HOME}/.all_bashrc";
fi

# Turn colors on or off (used for MACOSX)
export CLICOLOR=1

#
# Aliases
#
alias unmount="diskutil unmount"

# cd to the path of the front Finder window
cdf() {
  target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
  if [ "$target" != "" ]; then
    cd "$target"; pwd
  else
    echo 'No Finder window found' >&2
  fi
}

# pcat (pretty cat) for shell code syntax highlighting
# Depends on the installation of Pygment
#
# conda install Pygment
#
# https://gist.github.com/BretFisher/6f688dde0122399efdca5a9d26100437
# https://coderwall.com/p/7wvx0g/syntax-highlighting-in-the-terminal-with-pygments
#
# -g: auto detection of lexer from file contents
#
# Can pass in `-l` if you want to override the lexer:
#   
#     pcat -l sh test.R
#
pcat() { 
  pygmentize -f terminal256 -O style=native -g $* | less -R
}

# Allows auto-completion of ssh hostnames
# Depends on the following (installed during `install_osx_software.sh`):
# 
# ```
# brew install bash-completion
# brew tap homebrew/completions
# ```
#
# https://apple.stackexchange.com/a/209269
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    # Load RVM into a shell session *as a function*
    source "${HOME}/.rvm/scripts/rvm" ;
fi
